- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubernetes_dashboard_version: v2.0.0-rc1
    helm_install_url: https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
    istio_install_url: https://github.com/istio/istio/releases/download/1.4.3/istio-1.4.3-linux.tar.gz
  tasks:
  - name: Installer les packages pré-requis pour le module k8s
    apt:
      name: python3-kubernetes
      state: present
    when: ansible_os_family == "Debian"
    
  - name: Installer les packages Python
    pip:
      name: openshift
      extra_args: --user
      state: present

  - name: Creer l'utilisateur admin pour le tableau de bord Kubernetes
    k8s:
      state: present
      src: resources/dashboard-adminuser.yml
      
  - name: Télécharger le fichier de déploiement du dashboard
    get_url:
      url: "https://raw.githubusercontent.com/kubernetes/dashboard/{{ kubernetes_dashboard_version }}/aio/deploy/recommended.yaml"
      dest: /tmp/kubedashboard.yaml
      mode: '0644'

  - name: Installer le tableau de bord Kubernetes
    k8s:
      state: present
      src: /tmp/kubedashboard.yaml

  - name: Télécharger le client helm pour l'utilisateur
    unarchive:
      src: "{{ helm_install_url }}"
      dest: /tmp
      remote_src: yes

  - name: Installer le client helm pour l'utilisateur
    copy:
      src: /tmp/linux-amd64/helm
      dest: "{{ ansible_user_dir }}/bin/helm"
      remote_src: yes

  - name: Télécharger istioctl pour l'utilisateur
    unarchive:
      src: "{{ istio_install_url }}"
      dest: "{{ ansible_user_dir }}/bin"
      remote_src: yes

