apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: inspq
  labels:
    app: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube02
      containers:
        - name: jenkins
          image: elfelip01/jenkins:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
      initContainers:
        - name: initconfig
          image: elfelip01/jenkins:latest
          command:
            - bash
            - -c
            - sudo chown -R 1000:1000 /var/jenkins_home && git config --global user.name "Philippe Gauthier" && git config --global user.email "philippe.gauthier@inspq.qc.ca" && git config --global credential.helper store
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        #runAsUser: 0
        #fsGroup: 0
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
  namespace: inspq
  labels:
    app: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  namespace: inspq
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    namespace: inspq
    name: ingress-jenkins
    annotations:
        kubernetes.io/ingress.class: "nginx"
spec:
    rules:
    - host: jenkins.lacave
      http:
        paths:
        - path: /
          backend:
            serviceName: jenkins-service
            servicePort: 8080
