---
apiVersion: v1
kind: Namespace
metadata:
    name: pgo
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pgo-deployer-sa
    namespace: pgo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-deployer-cr
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - delete
      - patch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
      - bind
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
  - apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgreplicas
      - pgpolicies
      - pgtasks
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: pgo-deployer-crb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pgo-deployer-cr
subjects:
- kind: ServiceAccount
  name: pgo-deployer-sa
  namespace: pgo
---
apiVersion: batch/v1
kind: Job
metadata:
    name: pgo-deploy
    namespace: pgo
spec:
    backoffLimit: 0
    template:
        metadata:
            name: pgo-deploy
        spec:
            serviceAccountName: pgo-deployer-sa
            restartPolicy: Never
            containers:
            - name: pgo-deploy
              image: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0
              imagePullPolicy: IfNotPresent
              env:
                  - name: ARCHIVE_MODE
                    value: "true"
                  - name: ARCHIVE_TIMEOUT
                    value: "60"
                  - name: BACKREST
                    value: "true"
                  - name: BADGER
                    value: "false"
                  - name: CRUNCHY_DEBUG
                    value: "false"
                  - name: CREATE_RBAC
                    value: "true"
                  - name: CCP_IMAGE_PREFIX
                    value: "registry.developers.crunchydata.com/crunchydata"
                  - name: CCP_IMAGE_TAG
                    value: "centos7-12.3-4.3.0"
                  - name: DB_PASSWORD_LENGTH
                    value: "24"
                  - name: DB_PORT
                    value: "5432"
                  - name: DB_REPLICAS
                    value: "0"
                  - name: DB_USER
                    value: "testuser"
                  - name: DEFAULT_INSTANCE_MEMORY
                    value: "128Mi"
                  - name: DEFAULT_PGBACKREST_MEMORY
                    value: ""
                  - name: DEFAULT_PGBOUNCER_MEMORY
                    value: ""
                  - name: DEPLOY_ACTION
                    value: "install"
                  - name: DISABLE_AUTO_FAILOVER
                    value: "false"
                  - name: DISABLE_FSGROUP
                    value: "false"
                  - name: DYNAMIC_RBAC
                    value: "false"
                  - name: EXPORTERPORT
                    value: "9187"
                  - name: METRICS
                    value: "false"
                  - name: NAMESPACE
                    value: "pgo"
                  - name: NAMESPACE_MODE
                    value: "dynamic"
                  - name: PGBADGERPORT
                    value: "10000"
                  - name: PGO_ADMIN_PASSWORD
                    value: "password"
                  - name: PGO_ADMIN_PERMS
                    value: "*"
                  - name: PGO_ADMIN_ROLE_NAME
                    value: "pgoadmin"
                  - name: PGO_ADMIN_USERNAME
                    value: "admin"
                  - name: PGO_CLIENT_VERSION
                    value: "v4.3.0"
                  - name: PGO_IMAGE_PREFIX
                    value: "registry.developers.crunchydata.com/crunchydata"
                  - name: PGO_IMAGE_TAG
                    value: "centos7-4.3.0"
                  - name: PGO_INSTALLATION_NAME
                    value: "devtest"
                  - name: PGO_OPERATOR_NAMESPACE
                    value: "pgo"
                  - name: SCHEDULER_TIMEOUT
                    value: "3600"
                  - name: BACKREST_STORAGE
                    value: "local-path"
                  - name: BACKUP_STORAGE
                    value: "local-path"
                  - name: PRIMARY_STORAGE
                    value: "local-path"
                  - name: REPLICA_STORAGE
                    value: "local-path"
                  - name: WAL_STORAGE
                    value: ""
                  - name: STORAGE1_NAME
                    value: "local-path"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE1_SIZE
                    value: "1G"
                  - name: STORAGE1_TYPE
                    value: "dynamic"
                  - name: STORAGE1_CLASS
                    value: "local-path"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteOnce"
