---
apiVersion: v1
kind: Namespace
metadata:
    name: inspq
    labels:
        istio-injection: enabled
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: inspq
    name: nexus-deployment
    labels:
        app: nexus
spec:
    serviceName: nexus
    replicas: 1
    selector:
        matchLabels:
            app: nexus
    template:
        metadata:
            labels:
                app: nexus
        spec:
            securityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            volumes:
                - name: nexus-data
                  persistentVolumeClaim:
                    claimName: nexus3-claim
            containers:
            - name: nexus
              image: sonatype/nexus3:latest
              ports:
              - containerPort: 8081
              volumeMounts:
              - name: nexus-data
                mountPath: /nexus-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: nexus3-claim
    namespace: inspq
    labels:
        app: nexus
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
    storageClassName: local-path
---
    apiVersion: v1
    kind: Service
    metadata:
        namespace: inspq
        name: nexus-service
    spec:
        selector:
            app: nexus
        ports:
        - name: web
          protocol: TCP
          port: 8081
          targetPort: 8081
        - name: docker
          protocol: TCP
          port: 5000
          targetPort: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    namespace: inspq
    name: ingress-nexus
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
    rules:
    - host: nexus3.lacave
      http:
        paths:
        - path: /
          backend:
            serviceName: nexus-service
            servicePort: 8081
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    namespace: inspq
    name: ingress-docker-nexus
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
    tls:
    - hosts:
      - docker.lacave
      secretName: docker-lacave-tls
    rules:
    - host: docker.lacave
      http:
        paths:
        - path: /
          backend:
            serviceName: nexus-service
            servicePort: 5000
